apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notification
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # autoscaling.knative.dev/min-scale: "0"
        # autoscaling.knative.dev/scale-down-delay: "1m"
        # autoscaling.knative.dev/window: "40s"
    spec:
      containers:
      - image: ghcr.io/xvzup/knative_test:issue2
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        # command: ["gunicorn"]
        # args: ["example:app", "-b", "0.0.0.0:8080"]
        # readinessProbe:
        #   tcpSocket:
        #     port: 8000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 8000


            #gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app