apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notification
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target-utilization-percentage: "10"
    spec:
      containerConcurrency: 1
      containers:
      - image: ghcr.io/xvzup/knative_test:master
        imagePullPolicy: Always
        name: fastapi
        ports:
        - containerPort: 8000
          protocol: TCP
        command: ["uvicorn"]
        args: ["app:app", "--host", "0.0.0.0"]
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000