apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notification
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/xvzup/knative_test:issue2
        command: ["uvicorn"]
        args: ["--app-dir", "./App", "app:app", "--reload"]
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
