apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notification
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/xvzup/knative_test:issue2
        imagePullPolicy: Always
        name: fastapi
        ports:
        - containerPort: 8000
          protocol: TCP
        command: ["gunicorn"]
        args: ["app:app", "-b", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker"]
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000